// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.

//! `/v3/snapshots/detail` REST operations bindings of BlockStorage

use eyre::Result;
use serde::{Deserialize, Serialize};
use tokio::sync::mpsc::UnboundedSender;

use openstack_sdk::AsyncOpenStack;

use crate::action::Action;
use crate::cloud_worker::BlockStorageApiRequest;
use crate::cloud_worker::common::CloudWorkerError;
use crate::cloud_worker::types::{ApiRequest, ExecuteApiRequest};

pub mod delete;
pub mod list_detailed;

pub use delete::*;
pub use list_detailed::*;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum BlockStorageSnapshotApiRequest {
    /// Delete
    Delete(Box<BlockStorageSnapshotDelete>),
    /// ListDetailed
    ListDetailed(Box<BlockStorageSnapshotList>),
}

impl From<BlockStorageSnapshotApiRequest> for ApiRequest {
    fn from(item: BlockStorageSnapshotApiRequest) -> Self {
        ApiRequest::BlockStorage(BlockStorageApiRequest::from(item))
    }
}

impl From<BlockStorageSnapshotList> for BlockStorageSnapshotApiRequest {
    fn from(item: BlockStorageSnapshotList) -> Self {
        BlockStorageSnapshotApiRequest::ListDetailed(Box::new(item))
    }
}

impl From<BlockStorageSnapshotList> for BlockStorageApiRequest {
    fn from(item: BlockStorageSnapshotList) -> Self {
        BlockStorageApiRequest::Snapshot(Box::new(BlockStorageSnapshotApiRequest::from(item)))
    }
}

impl ExecuteApiRequest for BlockStorageSnapshotApiRequest {
    async fn execute_request(
        &self,
        session: &mut AsyncOpenStack,
        request: &ApiRequest,
        app_tx: &UnboundedSender<Action>,
    ) -> Result<(), CloudWorkerError> {
        match self {
            BlockStorageSnapshotApiRequest::Delete(req) => {
                req.execute_request(session, request, app_tx).await?;
            }
            BlockStorageSnapshotApiRequest::ListDetailed(req) => {
                req.execute_request(session, request, app_tx).await?;
            }
        }
        Ok(())
    }
}
