// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.

//! Action AddressGroup command
//!
//! Wraps invoking of the `v2.0/address-groups/{id}/remove_addresses` with `PUT` method

use clap::Args;
use eyre::WrapErr;
use tracing::info;

use openstack_sdk::AsyncOpenStack;

use crate::Cli;
use crate::OpenStackCliError;
use crate::output::OutputProcessor;

use openstack_sdk::api::QueryAsync;
use openstack_sdk::api::network::v2::address_group::remove_addresses;
use openstack_types::network::v2::address_group::response::remove_addresses::AddressGroupResponse;

/// Command without description in OpenAPI
#[derive(Args)]
pub struct AddressGroupCommand {
    /// Request Query parameters
    #[command(flatten)]
    query: QueryParameters,

    /// Path parameters
    #[command(flatten)]
    path: PathParameters,

    #[command(flatten)]
    address_group: AddressGroup,
}

/// Query parameters
#[derive(Args)]
struct QueryParameters {}

/// Path parameters
#[derive(Args)]
struct PathParameters {
    /// id parameter for /v2.0/address-groups/{id} API
    #[arg(
        help_heading = "Path parameters",
        id = "path_param_id",
        value_name = "ID"
    )]
    id: String,
}
/// AddressGroup Body data
#[derive(Args, Clone)]
struct AddressGroup {
    /// A list of IP addresses.
    ///
    /// Parameter is an array, may be provided multiple times.
    #[arg(action=clap::ArgAction::Append, help_heading = "Body parameters", long)]
    addresses: Option<Vec<String>>,
}

impl AddressGroupCommand {
    /// Perform command action
    pub async fn take_action(
        &self,
        parsed_args: &Cli,
        client: &mut AsyncOpenStack,
    ) -> Result<(), OpenStackCliError> {
        info!("Action AddressGroup");

        let op = OutputProcessor::from_args(
            parsed_args,
            Some("network.address_group"),
            Some("remove_addresses"),
        );
        op.validate_args(parsed_args)?;

        let mut ep_builder = remove_addresses::Request::builder();

        ep_builder.id(&self.path.id);

        // Set body parameters
        // Set Request.address_group data
        let args = &self.address_group;
        let mut address_group_builder = remove_addresses::AddressGroupBuilder::default();
        if let Some(val) = &args.addresses {
            address_group_builder.addresses(val.iter().map(Into::into).collect::<Vec<_>>());
        }

        ep_builder.address_group(
            address_group_builder
                .build()
                .wrap_err("error preparing the request data")?,
        );

        let ep = ep_builder
            .build()
            .map_err(|x| OpenStackCliError::EndpointBuild(x.to_string()))?;

        let data = ep.query_async(client).await?;
        op.output_single::<AddressGroupResponse>(data)?;
        // Show command specific hints
        op.show_command_hint()?;
        Ok(())
    }
}
