// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.

//! List Mappings command
//!
//! Wraps invoking of the `v4/federation/mappings` with `GET` method

use clap::Args;
use tracing::info;

use openstack_sdk::AsyncOpenStack;

use crate::Cli;
use crate::OpenStackCliError;
use crate::output::OutputProcessor;

use openstack_sdk::api::QueryAsync;
use openstack_sdk::api::identity::v4::federation::mapping::list;
use openstack_sdk::api::{Pagination, paged};
use openstack_types::identity::v4::federation::mapping::response::list::MappingResponse;

/// List available federation mappings.
///
/// Without `domain_id` specified global mappings are returned.
///
/// It is expected that listing mappings belonging to the other domain is only
/// allowed to the admin user.
#[derive(Args)]
#[command(about = "List federation mappings.")]
pub struct MappingsCommand {
    /// Request Query parameters
    #[command(flatten)]
    query: QueryParameters,

    /// Path parameters
    #[command(flatten)]
    path: PathParameters,

    /// Total limit of entities count to return. Use this when there are too many entries.
    #[arg(long, default_value_t = 10000)]
    max_items: usize,
}

/// Query parameters
#[derive(Args)]
struct QueryParameters {
    /// Filters the response by a mapping type.
    #[arg(help_heading = "Query parameters", long, value_parser = ["jwt","oidc"])]
    _type: Option<String>,

    /// Filters the response by a domain ID.
    #[arg(help_heading = "Query parameters", long)]
    domain_id: Option<String>,

    /// Filters the response by a idp ID.
    #[arg(help_heading = "Query parameters", long)]
    idp_id: Option<String>,

    /// Limit number of entries on the single response page (Maximal 100)
    #[arg(
        help_heading = "Query parameters",
        long("page-size"),
        visible_alias("limit")
    )]
    limit: Option<u32>,

    /// Page marker (id of the last entry on the previous page.
    #[arg(help_heading = "Query parameters", long)]
    marker: Option<String>,

    /// Filters the response by IDP name.
    #[arg(help_heading = "Query parameters", long)]
    name: Option<String>,
}

/// Path parameters
#[derive(Args)]
struct PathParameters {}

impl MappingsCommand {
    /// Perform command action
    pub async fn take_action(
        &self,
        parsed_args: &Cli,
        client: &mut AsyncOpenStack,
    ) -> Result<(), OpenStackCliError> {
        info!("List Mappings");

        let op = OutputProcessor::from_args(
            parsed_args,
            Some("identity.federation/mapping"),
            Some("list"),
        );
        op.validate_args(parsed_args)?;

        let mut ep_builder = list::Request::builder();

        // Set query parameters
        if let Some(val) = &self.query.domain_id {
            ep_builder.domain_id(val);
        }
        if let Some(val) = &self.query.idp_id {
            ep_builder.idp_id(val);
        }
        if let Some(val) = &self.query.name {
            ep_builder.name(val);
        }
        if let Some(val) = &self.query.limit {
            ep_builder.limit(*val);
        }
        if let Some(val) = &self.query.marker {
            ep_builder.marker(val);
        }
        if let Some(val) = &self.query._type {
            ep_builder._type(val);
        }

        let ep = ep_builder
            .build()
            .map_err(|x| OpenStackCliError::EndpointBuild(x.to_string()))?;

        let data: Vec<serde_json::Value> = paged(ep, Pagination::Limit(self.max_items))
            .query_async(client)
            .await?;
        op.output_list::<MappingResponse>(data)?;
        // Show command specific hints
        op.show_command_hint()?;
        Ok(())
    }
}
