// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.

//! Create BandwidthLimitRule command
//!
//! Wraps invoking of the `v2.0/qos/policies/{policy_id}/bandwidth_limit_rules` with `POST` method

use clap::Args;
use tracing::info;

use openstack_sdk::AsyncOpenStack;

use crate::Cli;
use crate::OpenStackCliError;
use crate::output::OutputProcessor;

use clap::ValueEnum;
use openstack_sdk::api::QueryAsync;
use openstack_sdk::api::network::v2::qos::policy::bandwidth_limit_rule::create;
use openstack_types::network::v2::qos::policy::bandwidth_limit_rule::response::create::BandwidthLimitRuleResponse;

/// Creates a bandwidth limit rule for a QoS policy.
///
/// Normal response codes: 201
///
/// Error response codes: 400, 401, 404, 409
#[derive(Args)]
#[command(about = "Create bandwidth limit rule")]
pub struct BandwidthLimitRuleCommand {
    /// Request Query parameters
    #[command(flatten)]
    query: QueryParameters,

    /// Path parameters
    #[command(flatten)]
    path: PathParameters,

    /// A `bandwidth_limit_rule` object.
    #[command(flatten)]
    bandwidth_limit_rule: BandwidthLimitRule,
}

/// Query parameters
#[derive(Args)]
struct QueryParameters {}

/// Path parameters
#[derive(Args)]
struct PathParameters {
    /// policy_id parameter for
    /// /v2.0/qos/policies/{policy_id}/bandwidth_limit_rules/{id} API
    #[arg(
        help_heading = "Path parameters",
        id = "path_param_policy_id",
        value_name = "POLICY_ID"
    )]
    policy_id: String,
}

#[derive(Clone, Eq, Ord, PartialEq, PartialOrd, ValueEnum)]
enum Direction {
    Egress,
    Ingress,
}

/// BandwidthLimitRule Body data
#[derive(Args, Clone)]
struct BandwidthLimitRule {
    /// The direction of the traffic to which the QoS rule is applied, as seen
    /// from the point of view of the `port`. Valid values are `egress` and
    /// `ingress`. Default value is `egress`.
    #[arg(help_heading = "Body parameters", long)]
    direction: Option<Direction>,

    /// The maximum burst size (in kilobits). Default is `0`.
    #[arg(help_heading = "Body parameters", long)]
    max_burst_kbps: Option<i32>,

    /// The maximum KBPS (kilobits per second) value. If you specify this
    /// value, must be greater than 0 otherwise max_kbps will have no value.
    #[arg(help_heading = "Body parameters", long)]
    max_kbps: Option<i32>,
}

impl BandwidthLimitRuleCommand {
    /// Perform command action
    pub async fn take_action(
        &self,
        parsed_args: &Cli,
        client: &mut AsyncOpenStack,
    ) -> Result<(), OpenStackCliError> {
        info!("Create BandwidthLimitRule");

        let op = OutputProcessor::from_args_with_resource_key(
            parsed_args,
            "network.qos/policy/bandwidth_limit_rule",
        );
        op.validate_args(parsed_args)?;

        let mut ep_builder = create::Request::builder();

        // Set path parameters
        ep_builder.policy_id(&self.path.policy_id);
        // Set query parameters
        // Set body parameters
        // Set Request.bandwidth_limit_rule data
        let args = &self.bandwidth_limit_rule;
        let mut bandwidth_limit_rule_builder = create::BandwidthLimitRuleBuilder::default();
        if let Some(val) = &args.max_kbps {
            bandwidth_limit_rule_builder.max_kbps(*val);
        }

        if let Some(val) = &args.max_burst_kbps {
            bandwidth_limit_rule_builder.max_burst_kbps(*val);
        }

        if let Some(val) = &args.direction {
            let tmp = match val {
                Direction::Egress => create::Direction::Egress,
                Direction::Ingress => create::Direction::Ingress,
            };
            bandwidth_limit_rule_builder.direction(tmp);
        }

        ep_builder.bandwidth_limit_rule(bandwidth_limit_rule_builder.build().unwrap());

        let ep = ep_builder
            .build()
            .map_err(|x| OpenStackCliError::EndpointBuild(x.to_string()))?;

        let data = ep.query_async(client).await?;
        op.output_single::<BandwidthLimitRuleResponse>(data)?;
        Ok(())
    }
}
