---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix', 'lf']
        exclude: '.*\.(svg)$'
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
        files: .*\.(yaml|yml)$
        exclude: '^zuul.d/.*$'
          #- repo: https://github.com/doublify/pre-commit-rust
          #  rev: master
          #  hooks:
          #    - id: fmt
          #    - id: cargo-check
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format rust files with cargo fmt
        entry: cargo fmt
        args: ["--"]
        language: rust
        types: [rust]
        minimum_pre_commit_version: 2.21.0
        require_serial: true
      - id: cargo-check
        name: cargo check
        description: Run cargo check for compilation errors
        entry: cargo check
        language: rust
        types: [rust]
        pass_filenames: false
        minimum_pre_commit_version: 2.21.0
        require_serial: true
      - id: cargo-clippy
        name: cargo clippy --lib
        description: Run cargo clippy lint tool
        entry: cargo clippy
        language: rust
        types: [rust]
        minimum_pre_commit_version: 2.21.0
        require_serial: true
        pass_filenames: false
