[workspace]
resolver = "2"
members = [
  "openstack_sdk",
  "openstack_cli",
  "structable_derive",
  "xtask",
  "fuzz"
]
default-members = ["openstack_cli", "openstack_sdk"]

[workspace.package]
license = "Apache-2.0"
edition = "2021"
authors = ["Artem Goncharov (gtema)"]
rust-version = "1.75"  # MSRV
homepage = "https://github.com/gtema/openstack"
repository = "https://github.com/gtema/openstack"

[workspace.dependencies]
async-trait = { version = "^0.1" } #, optional = true }
anyhow = "^1.0"
bytes = "^1.6"
chrono = { version = "^0.4", default-features = false, features = ["clock", "serde"] }
clap = { version = "^4.5", features = ["derive", "env"] }
dialoguer = "^0.11"
futures = "^0.3"
http = "^1.1"
json-patch = { version = "^1.4" }
reqwest = { version = "^0.12", features = ["blocking", "stream", "rustls-tls"], default-features = false }
serde = { version="^1.0", features=["derive"] }
serde_json = "^1.0"
serde_bytes = "^0.11"
tokio = { version = "^1.37", features = ["fs", "macros", "net", "sync", "rt-multi-thread", "io-std", "signal"]}
tokio-util = { version="^0.7", features = ["io", "compat"]}
thiserror = { version = "^1.0" }
tracing = "^0.1"
url = "^2.5"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.13.3"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
# Publish jobs to run in CI
pr-run-mode = "plan"
# Whether cargo-dist should create a Github Release or use an existing draft
create-release = false
# Whether to install an updater program
install-updater = true

[profile.dev]
debug = 0

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
