[workspace]
resolver = "2"
members = [
  "openstack_sdk",
  "openstack_cli",
  "structable_derive",
  "xtask"
]
default-members = ["openstack_cli", "openstack_sdk"]

[workspace.package]
license = "Apache-2.0"
edition = "2021"
authors = ["Artem Goncharov (gtema)"]
rust-version = "1.75"  # MSRV
homepage = "https://github.com/gtema/openstack"
repository = "https://github.com/gtema/openstack"

[workspace.dependencies]
async-trait = { version = "~0.1" } #, optional = true }
anyhow = "~1.0"
bytes = "~1.5"
chrono = { version = "~0.4", default-features = false, features = ["clock", "serde"] }
clap = { version = "~4.4", features = ["derive", "env"] }
dialoguer = "~0.11"
futures = "~0.3"
http = "~0.2"
json-patch = { version = "~1.2" }
reqwest = { version = "~0.11", features = ["blocking", "stream", "rustls-tls"], default-features = false }
serde = { version="~1.0", features=["derive"] }
serde_json = "~1.0"
serde_yaml = "~0.9"
serde_bytes = "~0.11"
tokio = { version = "~1.35", features = ["fs", "macros", "net", "sync", "rt-multi-thread", "io-std"]}
tokio-util = { version="~0.7", features = ["io", "compat"]}
thiserror = { version = "~1.0" }
tracing = "~0.1"
url = "~2.5"

[profile.dev]
debug = 0
