[workspace]
allow_dirty = true
# dependencies_update = false # run `cargo update`
git_release_enable = false
git_release_latest = false

[[package]]
name = "openstack-sdk-auth-core"
git_release_enable = true
version_group = "auth"

[[package]]
name = "openstack-sdk-auth-applicationcredential"
git_release_enable = true
version_group = "auth"

[[package]]
name = "openstack-sdk-auth-federation"
git_release_enable = true
version_group = "auth"

[[package]]
name = "openstack-sdk-auth-jwt"
git_release_enable = true
version_group = "auth"

[[package]]
name = "openstack-sdk-auth-oidcaccesstoken"
git_release_enable = true
version_group = "auth"

[[package]]
name = "openstack-sdk-auth-passkey"
git_release_enable = true
version_group = "auth"

[[package]]
name = "openstack-sdk-auth-websso"
git_release_enable = true
version_group = "auth"

[[package]]
name = "openstack-sdk-core"
git_release_enable = true
version_group = "sdks"

[[package]]
name = "openstack_sdk"
changelog_include = ["openstack-sdk-core"]
git_release_enable = true
version_group = "sdks"

[[package]]
name = "openstack_cli"
changelog_include = ["openstack_sdk"]
git_release_enable = true
version_group = "bins"

[[package]]
name = "openstack_tui"
changelog_include = ["openstack_tui"]
git_release_enable = true
version_group = "bins"

[[package]]
name = "openstack_types"
git_release_enable = true
version_group = "sdks"
