[workspace]
allow_dirty = true
# dependencies_update = false # run `cargo update`
git_release_enable = false
git_release_latest = false

# Main packages for which we want to have tags
[[package]]
name = "openstack_sdk"
changelog_include = ["openstack_sdk_core"]
git_release_enable = true
version_group = "sdk"

[[package]]
name = "openstack_cli"
changelog_include = ["openstack_sdk"]
git_release_enable = true
version_group = "bins"

[[package]]
name = "openstack_tui"
changelog_include = ["openstack_tui"]
git_release_enable = true
version_group = "bins"

[[package]]
name = "openstack_types"
git_release_enable = true
version_group = "sdk"

# remaining packages grouped for the version alignment

## CLI group
[[package]]
name = "openstack_cli"
version_group = "cli"
[[package]]
name = "openstack-cli-api"
version_group = "cli"
[[package]]
name = "openstack-cli-auth"
version_group = "cli"
[[package]]
name = "openstack-cli-block-storage"
version_group = "cli"
[[package]]
name = "openstack-cli-catalog"
version_group = "cli"
[[package]]
name = "openstack-cli-compute"
version_group = "cli"
[[package]]
name = "openstack-cli-container-infrastructure-management"
version_group = "cli"
[[package]]
name = "openstack-cli-core"
version_group = "cli"
[[package]]
name = "openstack-cli-dns"
version_group = "cli"
[[package]]
name = "openstack-cli-identity"
version_group = "cli"
[[package]]
name = "openstack-cli-image"
version_group = "cli"
[[package]]
name = "openstack-cli-load-balancer"
version_group = "cli"
[[package]]
name = "openstack-cli-network"
version_group = "cli"
[[package]]
name = "openstack-cli-object-store"
version_group = "cli"
[[package]]
name = "openstack-cli-placement"
version_group = "cli"

## SDK group
[[package]]
name = "openstack_sdk_core"
version_group = "sdk"
[[package]]
name = "openstack-sdk-auth-core"
version_group = "sdk-auth"

[[package]]
name = "openstack-sdk-auth-applicationcredential"
version_group = "sdk-auth"
[[package]]
name = "openstack-sdk-auth-federation"
version_group = "sdk-auth"
[[package]]
name = "openstack-sdk-auth-jwt"
version_group = "sdk-auth"
[[package]]
name = "openstack-sdk-auth-multifactor"
version_group = "sdk-auth"
[[package]]
name = "openstack-sdk-auth-oidcaccesstoken"

[[package]]
name = "openstack-sdk-auth-oidcclientcredentials"
version_group = "sdk-auth"
[[package]]
name = "openstack-sdk-auth-passkey"
version_group = "sdk-auth"
[[package]]
name = "openstack-sdk-auth-password"
version_group = "sdk-auth"
[[package]]
name = "openstack-sdk-auth-receipt"
version_group = "sdk-auth"
[[package]]
name = "openstack-sdk-auth-token"
version_group = "sdk-auth"
[[package]]
name = "openstack-sdk-auth-totp"
version_group = "sdk-auth"
[[package]]
name = "openstack-sdk-auth-websso"
version_group = "sdk-auth"
[[package]]
name = "openstack-sdk-block-storage"
version_group = "sdk"
[[package]]
name = "openstack-sdk-compute"
version_group = "sdk"
[[package]]
name = "openstack-sdk-container-infrastructure-management"
version_group = "sdk"
[[package]]
name = "openstack-sdk-dns"
version_group = "sdk"
[[package]]
name = "openstack-sdk-identity"
version_group = "sdk"
[[package]]
name = "openstack-sdk-image"
version_group = "sdk"
[[package]]
name = "openstack-sdk-load-balancer"
version_group = "sdk"
[[package]]
name = "openstack-sdk-network"
version_group = "sdk"
[[package]]
name = "openstack-sdk-object-store"
version_group = "sdk"
[[package]]
name = "openstack-sdk-placement"
version_group = "sdk"


## Types group

[[package]]
name = "openstack-types-core"
version_group = "sdk"
[[package]]
name = "openstack-types-block-storage"
version_group = "sdk"
[[package]]
name = "openstack-types-compute"
version_group = "sdk"
[[package]]
name = "openstack-types-container-infrastructure-management"
version_group = "sdk"
[[package]]
name = "openstack-types-dns"
version_group = "sdk"
[[package]]
name = "openstack-types-identity"
version_group = "sdk"
[[package]]
name = "openstack-types-image"
version_group = "sdk"
[[package]]
name = "openstack-types-load-balancer"
version_group = "sdk"
[[package]]
name = "openstack-types-network"
version_group = "sdk"
[[package]]
name = "openstack-types-object-store"
version_group = "sdk"
[[package]]
name = "openstack-types-placement"
version_group = "sdk"
