// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.
//! Response type for the POST `agents` operation

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::BTreeMap;
use structable::{StructTable, StructTableOptions};

/// Agent response representation
#[derive(Clone, Deserialize, Serialize, StructTable)]
pub struct AgentResponse {
    #[serde(default, deserialize_with = "crate::common::deser_bool_str_opt")]
    #[structable(optional)]
    pub admin_state_up: Option<bool>,

    #[serde(default)]
    #[structable(optional)]
    pub agent_type: Option<String>,

    #[serde(default)]
    #[structable(optional)]
    pub alive: Option<bool>,

    #[serde(default)]
    #[structable(optional)]
    pub availability_zone: Option<String>,

    #[serde(default)]
    #[structable(optional)]
    pub binary: Option<String>,

    #[serde(default)]
    #[structable(optional, serialize)]
    pub configurations: Option<BTreeMap<String, Value>>,

    #[serde(default)]
    #[structable(optional)]
    pub created_at: Option<String>,

    #[serde(default)]
    #[structable(optional)]
    pub description: Option<String>,

    #[serde(default)]
    #[structable(optional)]
    pub heartbeat_timestamp: Option<String>,

    #[serde(default)]
    #[structable(optional)]
    pub host: Option<String>,

    #[serde(default)]
    #[structable(optional)]
    pub id: Option<String>,

    #[serde(default)]
    #[structable(optional)]
    pub resources_synced: Option<String>,

    #[serde(default)]
    #[structable(optional)]
    pub started_at: Option<String>,

    #[serde(default)]
    #[structable(optional)]
    pub topic: Option<String>,
}
