// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.
//! Response type for the GET `service-providers` operation

use serde::{Deserialize, Serialize};
use structable::{StructTable, StructTableOptions};

/// ServiceProvider response representation
#[derive(Clone, Deserialize, Serialize, StructTable)]
pub struct ServiceProviderResponse {
    /// Defines whether the provider is the default for the service type. If
    /// this value is `true`, the provider is the default. If this value is
    /// `false`, the provider is not the default.
    ///
    #[serde(rename = "default")]
    #[structable(optional, title = "default", wide)]
    pub _default: Option<String>,

    /// Human-readable name of the resource.
    ///
    #[structable(optional)]
    pub name: Option<String>,

    /// The service type, which is `CORE`, `DUMMY`, `FIREWALL`, `FLAVORS`,
    /// `L3_ROUTER_NAT`, `METERING`, `QOS`, or `VPN`.
    ///
    #[structable(optional)]
    pub service_type: Option<String>,
}
