// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.
//! Response type for the GET `os-hypervisors/{id}` operation

use serde::{Deserialize, Serialize};
use structable::{StructTable, StructTableOptions};

/// Hypervisor response representation
#[derive(Clone, Deserialize, Serialize, StructTable)]
pub struct HypervisorResponse {
    /// A dictionary that contains cpu information like `arch`, `model`,
    /// `vendor`, `features` and `topology`. The content of this field is
    /// hypervisor specific.
    ///
    /// Note
    ///
    /// Since version 2.28 `cpu_info` field is returned as a dictionary instead
    /// of string.
    ///
    /// **Available until version 2.87**
    #[structable()]
    pub cpu_info: String,

    /// The current_workload is the number of tasks the hypervisor is
    /// responsible for. This will be equal or greater than the number of
    /// active VMs on the system (it can be greater when VMs are being deleted
    /// and the hypervisor is still cleaning up).
    ///
    /// **Available until version 2.87**
    #[structable(optional)]
    pub current_workload: Option<i32>,

    /// The actual free disk on this hypervisor(in GiB). If allocation ratios
    /// used for overcommit are configured, this may be negative. This is
    /// intentional as it provides insight into the amount by which the disk is
    /// overcommitted.
    ///
    /// **Available until version 2.87**
    #[serde(default)]
    #[structable(optional)]
    pub disk_available_least: Option<i32>,

    /// The free disk remaining on this hypervisor(in GiB). This does not take
    /// allocation ratios used for overcommit into account so this value may be
    /// negative.
    ///
    /// **Available until version 2.87**
    #[structable(optional)]
    pub free_disk_gb: Option<i32>,

    /// The free RAM in this hypervisor(in MiB). This does not take allocation
    /// ratios used for overcommit into account so this value may be negative.
    ///
    /// **Available until version 2.87**
    #[structable(optional)]
    pub free_ram_mb: Option<i32>,

    /// The IP address of the hypervisor’s host.
    #[structable(optional)]
    pub host_ip: Option<String>,

    /// The hypervisor host name provided by the Nova virt driver. For the
    /// Ironic driver, it is the Ironic node uuid.
    #[structable()]
    pub hypervisor_hostname: String,

    /// The hypervisor type.
    #[structable()]
    pub hypervisor_type: String,

    /// The hypervisor version.
    #[serde(deserialize_with = "openstack_types_core::common::deser_num_str")]
    #[structable()]
    pub hypervisor_version: i64,

    /// The id of the hypervisor as a UUID.
    ///
    /// **New in version 2.53**
    #[structable()]
    pub id: i32,

    /// The disk in this hypervisor (in GiB). This does not take allocation
    /// ratios used for overcommit into account so there may be disparity
    /// between this and the used count.
    ///
    /// **Available until version 2.87**
    #[structable()]
    pub local_gb: i32,

    /// The disk used in this hypervisor (in GiB).
    ///
    /// **Available until version 2.87**
    #[structable()]
    pub local_gb_used: i32,

    /// The memory of this hypervisor (in MiB). This does not take allocation
    /// ratios used for overcommit into account so there may be disparity
    /// between this and the used count.
    ///
    /// **Available until version 2.87**
    #[structable()]
    pub memory_mb: i32,

    /// The memory used in this hypervisor (in MiB).
    ///
    /// **Available until version 2.87**
    #[structable()]
    pub memory_mb_used: i32,

    /// The number of running VMs on this hypervisor.
    ///
    /// **Available until version 2.87**
    #[structable(optional)]
    pub running_vms: Option<i32>,

    /// The hypervisor service object.
    #[structable(serialize)]
    pub service: Service,

    /// The state of the hypervisor. One of `up` or `down`.
    #[structable(serialize)]
    pub state: State,

    /// The status of the hypervisor. One of `enabled` or `disabled`.
    #[structable(serialize)]
    pub status: Status,

    /// The number of vCPU in this hypervisor. This does not take allocation
    /// ratios used for overcommit into account so there may be disparity
    /// between this and the used count.
    ///
    /// **Available until version 2.87**
    #[structable()]
    pub vcpus: i32,

    /// The number of vCPU used in this hypervisor.
    ///
    /// **Available until version 2.87**
    #[structable()]
    pub vcpus_used: i32,
}

/// The hypervisor service object.
/// `Service` type
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Service {
    pub disabled_reason: Option<String>,
    pub host: String,
    pub id: i32,
}

#[derive(Debug, Deserialize, Clone, Serialize)]
pub enum State {
    // Down
    #[serde(rename = "down")]
    Down,

    // Up
    #[serde(rename = "up")]
    Up,
}

impl std::str::FromStr for State {
    type Err = ();
    fn from_str(input: &str) -> Result<Self, Self::Err> {
        match input {
            "down" => Ok(Self::Down),
            "up" => Ok(Self::Up),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Deserialize, Clone, Serialize)]
pub enum Status {
    // Disabled
    #[serde(rename = "disabled")]
    Disabled,

    // Enabled
    #[serde(rename = "enabled")]
    Enabled,
}

impl std::str::FromStr for Status {
    type Err = ();
    fn from_str(input: &str) -> Result<Self, Self::Err> {
        match input {
            "disabled" => Ok(Self::Disabled),
            "enabled" => Ok(Self::Enabled),
            _ => Err(()),
        }
    }
}
