// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.
//! Response type for the GET `servers/detail` operation

use serde::{Deserialize, Serialize};
use structable::{StructTable, StructTableOptions};

/// Server response representation
#[derive(Clone, Deserialize, Serialize, StructTable)]
pub struct ServerResponse {
    #[structable(wide)]
    pub created: String,

    #[structable()]
    pub id: String,

    #[structable()]
    pub status: String,

    #[structable(wide)]
    pub tenant_id: String,
}

#[derive(Debug, Deserialize, Clone, Serialize)]
pub enum Rel {
    // Bookmark
    #[serde(rename = "bookmark")]
    Bookmark,

    // Current
    #[serde(rename = "self")]
    Current,
}

impl std::str::FromStr for Rel {
    type Err = ();
    fn from_str(input: &str) -> Result<Self, Self::Err> {
        match input {
            "bookmark" => Ok(Self::Bookmark),
            "self" => Ok(Self::Current),
            _ => Err(()),
        }
    }
}

/// `Links` type
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Links {
    pub href: String,
    pub rel: Rel,
}
