// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.

//! `/v2.1/servers/detail` REST operations bindings of Compute

use eyre::Result;
use serde::{Deserialize, Serialize};
use tokio::sync::mpsc::UnboundedSender;

use openstack_sdk::AsyncOpenStack;

use crate::action::Action;
use crate::cloud_worker::common::CloudWorkerError;
use crate::cloud_worker::types::{ApiRequest, ExecuteApiRequest};
use crate::cloud_worker::ComputeApiRequest;

pub mod delete;
pub mod get;
pub mod get_console_output;
pub mod instance_action;
pub mod list_detailed;

pub use delete::*;
pub use get::*;
pub use get_console_output::*;
pub use instance_action::*;
pub use list_detailed::*;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ComputeServerApiRequest {
    /// Delete
    Delete(Box<ComputeServerDelete>),
    /// Get
    Get(Box<ComputeServerShow>),
    /// GetConsoleOutput
    GetConsoleOutput(Box<ComputeServerGetConsoleOutput>),
    /// InstanceAction
    InstanceAction(Box<ComputeServerInstanceActionApiRequest>),
    /// ListDetailed
    ListDetailed(Box<ComputeServerList>),
}

impl From<ComputeServerApiRequest> for ApiRequest {
    fn from(item: ComputeServerApiRequest) -> Self {
        ApiRequest::Compute(ComputeApiRequest::from(item))
    }
}

impl From<ComputeServerGetConsoleOutput> for ComputeServerApiRequest {
    fn from(item: ComputeServerGetConsoleOutput) -> Self {
        ComputeServerApiRequest::GetConsoleOutput(Box::new(item))
    }
}

impl From<ComputeServerInstanceActionApiRequest> for ComputeServerApiRequest {
    fn from(item: ComputeServerInstanceActionApiRequest) -> Self {
        ComputeServerApiRequest::InstanceAction(Box::new(item))
    }
}

impl From<ComputeServerList> for ComputeServerApiRequest {
    fn from(item: ComputeServerList) -> Self {
        ComputeServerApiRequest::ListDetailed(Box::new(item))
    }
}

impl From<ComputeServerGetConsoleOutput> for ComputeApiRequest {
    fn from(item: ComputeServerGetConsoleOutput) -> Self {
        ComputeApiRequest::Server(Box::new(ComputeServerApiRequest::from(item)))
    }
}

impl From<ComputeServerInstanceActionApiRequest> for ComputeApiRequest {
    fn from(item: ComputeServerInstanceActionApiRequest) -> Self {
        ComputeApiRequest::Server(Box::new(ComputeServerApiRequest::from(item)))
    }
}

impl From<ComputeServerList> for ComputeApiRequest {
    fn from(item: ComputeServerList) -> Self {
        ComputeApiRequest::Server(Box::new(ComputeServerApiRequest::from(item)))
    }
}

impl ExecuteApiRequest for ComputeServerApiRequest {
    async fn execute_request(
        &self,
        session: &mut AsyncOpenStack,
        request: &ApiRequest,
        app_tx: &UnboundedSender<Action>,
    ) -> Result<(), CloudWorkerError> {
        match self {
            ComputeServerApiRequest::Delete(ref req) => {
                req.execute_request(session, request, app_tx).await?;
            }
            ComputeServerApiRequest::Get(ref req) => {
                req.execute_request(session, request, app_tx).await?;
            }
            ComputeServerApiRequest::GetConsoleOutput(ref req) => {
                req.execute_request(session, request, app_tx).await?;
            }
            ComputeServerApiRequest::InstanceAction(ref req) => {
                req.execute_request(session, request, app_tx).await?;
            }
            ComputeServerApiRequest::ListDetailed(ref req) => {
                req.execute_request(session, request, app_tx).await?;
            }
        }
        Ok(())
    }
}
