// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! Every TUI resource's `Item` is `serde_json::Value`. Column set/titles/pointers/status/id are
//! computed fresh from `.config/config.yaml`'s `ViewConfig` on every call here -- nothing baked
//! into Rust source, nothing generated by codegen. Table columns tolerate whatever shape a
//! response actually has at any microversion, since they read the raw JSON by pointer instead of
//! deserializing into a typed struct.

use crate::config::ViewConfig;
use serde_json::Value;

/// Stringify whatever's at `pointer` in `value`: `None` for missing/null, plain text for a JSON
/// string or other scalar, pretty-vs-compact JSON (per `view.pretty_mode()`) for an object/array.
fn stringify(value: &Value, pointer: &str, pretty: bool) -> Option<String> {
    match value.pointer(pointer) {
        None | Some(Value::Null) => None,
        Some(Value::String(s)) => Some(s.clone()),
        Some(complex @ (Value::Object(_) | Value::Array(_))) => Some(if pretty {
            serde_json::to_string_pretty(complex).unwrap_or_else(|_| complex.to_string())
        } else {
            complex.to_string()
        }),
        Some(other) => Some(other.to_string()),
    }
}

/// Column list = `view.default_fields`, verbatim order and casing.
pub fn headers(view: &ViewConfig) -> Vec<String> {
    view.default_fields.clone()
}

/// One row's cell values, same column list/order as `headers(view)`. Pointer is
/// `view.field_data_json_pointer(title)` if configured, else `/{title}`.
pub fn row(value: &Value, view: &ViewConfig) -> Vec<Option<String>> {
    let pretty = view.pretty_mode();
    view.default_fields
        .iter()
        .map(|title| {
            let pointer = view
                .field_data_json_pointer(title)
                .unwrap_or_else(|| format!("/{title}"));
            stringify(value, &pointer, pretty)
        })
        .collect()
}

/// Row-status coloring hook: the value at `view.status_field`, plain text, `None` if unset or
/// missing.
pub fn status(value: &Value, view: &ViewConfig) -> Option<String> {
    let field = view.status_field.as_ref()?;
    stringify(value, &format!("/{field}"), false)
}

/// Row identifier for select/delete/describe. `view.id_field` if configured, else the `id`->`uuid`
/// fallback convention `table_view.rs` already used.
pub fn id(value: &Value, view: &ViewConfig) -> Option<String> {
    if let Some(field) = &view.id_field {
        return get_str(value, &format!("/{field}")).map(String::from);
    }
    value
        .get("id")
        .or_else(|| value.get("uuid"))
        .and_then(Value::as_str)
        .map(String::from)
}

pub fn get<'a>(value: &'a Value, pointer: &str) -> Option<&'a Value> {
    value.pointer(pointer)
}

pub fn get_str<'a>(value: &'a Value, pointer: &str) -> Option<&'a str> {
    get(value, pointer).and_then(Value::as_str)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg(
        default_fields: &[&str],
        status_field: Option<&str>,
        id_field: Option<&str>,
    ) -> ViewConfig {
        ViewConfig {
            default_fields: default_fields.iter().map(|s| s.to_string()).collect(),
            status_field: status_field.map(String::from),
            id_field: id_field.map(String::from),
            fields: vec![],
        }
    }

    #[test]
    fn headers_returns_default_fields_verbatim_order() {
        let view = cfg(&["name", "id", "status"], None, None);
        assert_eq!(headers(&view), vec!["name", "id", "status"]);
    }

    #[test]
    fn row_reads_scalar_and_missing_columns() {
        let view = cfg(&["id", "missing"], None, None);
        let value = serde_json::json!({"id": "abc"});
        assert_eq!(row(&value, &view), vec![Some("abc".to_string()), None]);
    }

    #[test]
    fn row_respects_json_pointer_override() {
        use crate::config::FieldConfig;
        let view = ViewConfig {
            default_fields: vec!["flavor".into()],
            fields: vec![FieldConfig {
                name: "flavor".into(),
                json_pointer: Some("/original_name".into()),
                ..Default::default()
            }],
            ..Default::default()
        };
        let value = serde_json::json!({"flavor": {"id": "1"}, "original_name": "m1.small"});
        assert_eq!(row(&value, &view), vec![Some("m1.small".to_string())]);
    }

    #[test]
    fn row_pretty_prints_objects_and_arrays() {
        let view = cfg(&["metadata"], None, None);
        let value = serde_json::json!({"metadata": {"a": 1}});
        assert_eq!(
            row(&value, &view),
            vec![Some(
                serde_json::to_string_pretty(&serde_json::json!({"a": 1})).unwrap()
            )]
        );
    }

    #[test]
    fn status_reads_configured_field() {
        let view = cfg(&["id"], Some("status"), None);
        let value = serde_json::json!({"id": "abc", "status": "ACTIVE"});
        assert_eq!(status(&value, &view), Some("ACTIVE".to_string()));
    }

    #[test]
    fn status_none_when_unset_or_missing() {
        let view = cfg(&["id"], None, None);
        let value = serde_json::json!({"id": "abc"});
        assert_eq!(status(&value, &view), None);

        let view = cfg(&["id"], Some("status"), None);
        let value = serde_json::json!({"id": "abc"});
        assert_eq!(status(&value, &view), None);
    }

    #[test]
    fn id_falls_back_to_id_then_uuid() {
        let view = cfg(&[], None, None);
        assert_eq!(
            id(&serde_json::json!({"id": "a"}), &view),
            Some("a".to_string())
        );
        assert_eq!(
            id(&serde_json::json!({"uuid": "b"}), &view),
            Some("b".to_string())
        );
        assert_eq!(id(&serde_json::json!({}), &view), None);
    }

    #[test]
    fn id_uses_configured_id_field_when_set() {
        let view = cfg(&[], None, Some("hypervisor_hostname"));
        let value = serde_json::json!({"id": "1", "hypervisor_hostname": "host-a"});
        assert_eq!(id(&value, &view), Some("host-a".to_string()));
    }

    #[test]
    fn get_and_get_str_read_by_pointer() {
        let value = serde_json::json!({"id": "abc"});
        assert_eq!(get(&value, "/id"), Some(&Value::String("abc".into())));
        assert_eq!(get_str(&value, "/id"), Some("abc"));
        assert_eq!(get_str(&value, "/missing"), None);
    }
}
