// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.
//! Response type for the get metadefs/namespaces/{namespace_name}/properties/{property_name} operation

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Property response representation
#[derive(Clone, Deserialize, Serialize)]
struct PropertyResponse {
    #[serde(rename = "additionalItems")]
    additional_items: Option<bool>,

    #[serde(rename = "default")]
    _default: Option<Value>,

    description: Option<String>,

    #[serde(rename = "enum")]
    _enum: Option<Vec<String>>,

    items: Option<Items>,

    maximum: Option<f32>,

    #[serde(rename = "maxItems")]
    max_items: Option<i32>,

    #[serde(rename = "maxLength")]
    max_length: Option<i32>,

    minimum: Option<f32>,

    #[serde(rename = "minItems")]
    min_items: Option<i32>,

    #[serde(rename = "minLength")]
    min_length: Option<i32>,

    name: String,

    operators: Option<Vec<String>>,

    pattern: Option<String>,

    readonly: Option<bool>,

    required: Option<Vec<String>>,

    title: String,

    #[serde(rename = "type")]
    _type: Type,

    #[serde(rename = "uniqueItems")]
    unique_items: Option<bool>,
}

#[derive(Debug, Deserialize, Clone, Serialize)]
#[serde(untagged)]
pub enum Type {
    // Array
    #[serde(rename = "array")]
    Array,

    // Number
    #[serde(rename = "number")]
    Number,

    // String
    #[serde(rename = "string")]
    String,

    // Boolean
    #[serde(rename = "boolean")]
    Boolean,

    // Integer
    #[serde(rename = "integer")]
    Integer,

    // Object
    #[serde(rename = "object")]
    Object,
}

/// `Items` type
#[derive(Clone, Debug, Deserialize, Serialize)]
struct Items {
    _enum: Option<Vec<String>>,
    _type: Option<Type>,
}
