// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.

//! Action Server command
//!
//! Wraps invoking of the `v2.1/servers/{id}/action` with `POST` method

use clap::Args;
use tracing::info;

use openstack_sdk::AsyncOpenStack;

use crate::Cli;
use crate::OpenStackCliError;
use crate::output::OutputProcessor;

use openstack_sdk::api::QueryAsync;
use openstack_sdk::api::compute::v2::server::confirm_resize;
use serde_json::Value;

/// Confirms a pending resize action for a server.
///
/// Specify the `confirmResize` action in the request body.
///
/// After you make this request, you typically must keep polling the server
/// status to determine whether the request succeeded. A successfully
/// confirming resize operation shows a status of `ACTIVE` or `SHUTOFF` and a
/// migration status of `confirmed`. You can also see the resized server in the
/// compute node that OpenStack Compute manages.
///
/// **Preconditions**
///
/// You can only confirm the resized server where the status is
/// `VERIFY_RESIZE`.
///
/// If the server is locked, you must have administrator privileges to confirm
/// the server.
///
/// **Troubleshooting**
///
/// If the server status remains `VERIFY_RESIZE`, the request failed. Ensure
/// you meet the preconditions and run the request again. If the request fails
/// again, the server status should be `ERROR` and a migration status of
/// `error`. Investigate the compute back end or ask your cloud provider. There
/// are some options for trying to correct the server status:
///
/// Note that the cloud provider may still need to cleanup any orphaned
/// resources on the source hypervisor.
///
/// Normal response codes: 204
///
/// Error response codes: badRequest(400), unauthorized(401), forbidden(403),
/// itemNotFound(404), conflict(409)
#[derive(Args)]
#[command(about = "Confirm Resized Server (confirmResize Action)")]
pub struct ServerCommand {
    /// Request Query parameters
    #[command(flatten)]
    query: QueryParameters,

    /// Path parameters
    #[command(flatten)]
    path: PathParameters,

    #[arg(help_heading = "Body parameters", long, value_name="JSON", value_parser=crate::common::parse_json)]
    confirm_resize: Value,
}

/// Query parameters
#[derive(Args)]
struct QueryParameters {}

/// Path parameters
#[derive(Args)]
struct PathParameters {
    /// id parameter for /v2.1/servers/{id}/action API
    #[arg(
        help_heading = "Path parameters",
        id = "path_param_id",
        value_name = "ID"
    )]
    id: String,
}

impl ServerCommand {
    /// Perform command action
    pub async fn take_action(
        &self,
        parsed_args: &Cli,
        client: &mut AsyncOpenStack,
    ) -> Result<(), OpenStackCliError> {
        info!("Action Server");

        let op = OutputProcessor::from_args(parsed_args);
        op.validate_args(parsed_args)?;

        let mut ep_builder = confirm_resize::Request::builder();

        // Set path parameters
        ep_builder.id(&self.path.id);
        // Set query parameters
        // Set body parameters
        // Set Request.confirm_resize data
        ep_builder.confirm_resize(self.confirm_resize.clone());

        let ep = ep_builder
            .build()
            .map_err(|x| OpenStackCliError::EndpointBuild(x.to_string()))?;
        openstack_sdk::api::ignore(ep).query_async(client).await?;
        Ok(())
    }
}
