[book]
authors = ["gtema"]
language = "en"
multilingual = false
src = "src"
title = "OpenStack Client Tools"

[rust]
edition = "2024" 

[build]
build-dir = "html"
create-missing = false

[output.html.fold]
enable = true
level = 2

[preprocessor.osc-cli]
command = "cargo run -p xtask --bin osc-cli-md"
