// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.

//! List Flavors command
//!
//! Wraps invoking of the `v2.1/flavors/detail` with `GET` method

use clap::Args;
use serde::{Deserialize, Serialize};
use tracing::info;

use anyhow::Result;

use openstack_sdk::AsyncOpenStack;

use crate::output::OutputProcessor;
use crate::Cli;
use crate::OpenStackCliError;
use crate::OutputConfig;
use crate::StructTable;

use crate::common::IntString;
use crate::common::NumString;
use openstack_sdk::api::compute::v2::flavor::list_detailed;
use openstack_sdk::api::QueryAsync;
use openstack_sdk::api::{paged, Pagination};
use serde_json::Value;
use std::collections::HashMap;
use std::fmt;
use structable_derive::StructTable;

/// Lists flavors with details.
///
/// Normal response codes: 200
///
/// Error response codes: badRequest(400), unauthorized(401), forbidden(403)
#[derive(Args)]
#[command(about = "List Flavors With Details")]
pub struct FlavorsCommand {
    /// Request Query parameters
    #[command(flatten)]
    query: QueryParameters,

    /// Path parameters
    #[command(flatten)]
    path: PathParameters,

    /// Total limit of entities count to return. Use this when there are too many entries.
    #[arg(long, default_value_t = 10000)]
    max_items: usize,
}

/// Query parameters
#[derive(Args)]
struct QueryParameters {
    #[arg(long)]
    limit: Option<i32>,

    #[arg(long)]
    marker: Option<String>,

    #[arg(long)]
    is_public: Option<String>,

    #[arg(long)]
    min_ram: Option<String>,

    #[arg(long)]
    min_disk: Option<String>,

    #[arg(long)]
    sort_key: Option<String>,

    #[arg(long)]
    sort_dir: Option<String>,
}

/// Path parameters
#[derive(Args)]
struct PathParameters {}
/// Flavors response representation
#[derive(Deserialize, Serialize, Clone, StructTable)]
struct ResponseData {
    /// The display name of a flavor.
    #[serde()]
    #[structable(optional)]
    name: Option<String>,

    /// The ID of the flavor. While people often make this look like
    /// an int, this is really a string.
    #[serde()]
    #[structable(optional)]
    id: Option<String>,

    /// The amount of RAM a flavor has, in MiB.
    #[serde()]
    #[structable(optional, wide)]
    ram: Option<IntString>,

    /// The number of virtual CPUs that will be allocated to the server.
    #[serde()]
    #[structable(optional, wide)]
    vcpus: Option<IntString>,

    /// The size of the root disk that will be created in GiB. If 0 the
    /// root disk will be set to exactly the size of the image used to
    /// deploy the instance. However, in this case the scheduler cannot
    /// select the compute host based on the virtual image size. Therefore,
    /// 0 should only be used for volume booted instances or for testing
    /// purposes. Volume-backed instances can be enforced for flavors with
    /// zero root disk via the
    /// `os\_compute\_api:servers:create:zero\_disk\_flavor`
    /// policy rule.
    #[serde()]
    #[structable(optional, wide)]
    disk: Option<IntString>,

    /// The size of the ephemeral disk that will be created, in
    /// GiB. Ephemeral disks may be written over on server state
    /// changes. So should only be used as a scratch space for
    /// applications that are aware of its limitations. Defaults to 0.
    #[serde(rename = "OS-FLV-EXT-DATA:ephemeral")]
    #[structable(optional, title = "OS-FLV-EXT-DATA:ephemeral", wide)]
    os_flv_ext_data_ephemeral: Option<IntString>,

    /// The size of a dedicated swap disk that will be allocated, in
    /// MiB. If 0 (the default), no dedicated swap disk will be created.
    /// Currently, the empty string (‘’) is used to represent 0.
    /// As of microversion 2.75 default return value of swap is 0
    /// instead of empty string.
    #[serde()]
    #[structable(optional, wide)]
    swap: Option<IntString>,

    /// The receive / transmit factor (as a float) that will be set on
    /// ports if the network backend supports the QOS extension.
    /// Otherwise it will be ignored. It defaults to 1.0.
    #[serde()]
    #[structable(optional, wide)]
    rxtx_factor: Option<NumString>,

    /// Whether the flavor is public (available to all projects) or scoped
    /// to a set of projects. Default is True if not specified.
    #[serde(rename = "os-flavor-access:is_public")]
    #[structable(optional, title = "os-flavor-access:is_public", wide)]
    os_flavor_access_is_public: Option<bool>,

    /// A dictionary of the flavor’s extra-specs key-and-value pairs. This will
    /// only be included if the user is allowed by policy to index flavor
    /// extra\_specs.
    ///
    ///
    /// **New in version 2.61**
    #[serde()]
    #[structable(optional, wide)]
    extra_specs: Option<HashMapStringNumString>,

    /// Links to the resources in question. See [API Guide / Links and
    /// References](https://docs.openstack.org/api-
    /// guide/compute/links_and_references.html)
    /// for more info.
    #[serde()]
    #[structable(optional, wide)]
    links: Option<Value>,
}
/// HashMap of NumString response type
#[derive(Default, Clone, Deserialize, Serialize)]
struct HashMapStringNumString(HashMap<String, NumString>);
impl fmt::Display for HashMapStringNumString {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{{{}}}",
            self.0
                .iter()
                .map(|v| format!("{}={}", v.0, v.1))
                .collect::<Vec<String>>()
                .join("\n")
        )
    }
}

impl FlavorsCommand {
    /// Perform command action
    pub async fn take_action(
        &self,
        parsed_args: &Cli,
        client: &mut AsyncOpenStack,
    ) -> Result<(), OpenStackCliError> {
        info!("List Flavors");

        let op = OutputProcessor::from_args(parsed_args);
        op.validate_args(parsed_args)?;

        let mut ep_builder = list_detailed::Request::builder();

        // Set path parameters
        // Set query parameters
        if let Some(val) = &self.query.limit {
            ep_builder.limit(*val);
        }
        if let Some(val) = &self.query.marker {
            ep_builder.marker(val.clone());
        }
        if let Some(val) = &self.query.is_public {
            ep_builder.is_public(val.clone());
        }
        if let Some(val) = &self.query.min_ram {
            ep_builder.min_ram(val.clone());
        }
        if let Some(val) = &self.query.min_disk {
            ep_builder.min_disk(val.clone());
        }
        if let Some(val) = &self.query.sort_key {
            ep_builder.sort_key(val.clone());
        }
        if let Some(val) = &self.query.sort_dir {
            ep_builder.sort_dir(val.clone());
        }
        // Set body parameters

        let ep = ep_builder
            .build()
            .map_err(|x| OpenStackCliError::EndpointBuild(x.to_string()))?;

        let data: Vec<serde_json::Value> = paged(ep, Pagination::Limit(self.max_items))
            .query_async(client)
            .await?;

        op.output_list::<ResponseData>(data)?;
        Ok(())
    }
}
