# Partial file included by cargo-dist into the generated workflow
#
- name: Harden Runner
  uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
  with:
    egress-policy: audit
