[package]
name = "openstack-sdk-plugin-wasm"
description = "Runtime loader and registry for Extism (WASM) OpenStack SDK plugins"
version = "0.1.0"
keywords = ["api", "openstack"]
categories = ["api-bindings"]
authors = ["Artem Goncharov (gtema)"]
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
dirs.workspace = true
extism.workspace = true
openstack-sdk-auth-core.workspace = true
reqwest = { workspace = true, features = ["rustls", "blocking"] }
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }
tracing.workspace = true
url.workspace = true

[dev-dependencies]
httpmock.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
