// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// WARNING: This file is automatically generated from OpenAPI schema using
// `openstack-codegenerator`.

//! Show Property command
//!
//! Wraps invoking of the `v2/metadefs/namespaces/{namespace_name}/properties/{property_name}` with `GET` method

use clap::Args;
use serde::{Deserialize, Serialize};
use tracing::info;

use openstack_sdk::AsyncOpenStack;

use crate::output::OutputProcessor;
use crate::Cli;
use crate::OpenStackCliError;
use crate::OutputConfig;
use crate::StructTable;

use openstack_sdk::api::image::v2::metadef::namespace::property::get;
use openstack_sdk::api::QueryAsync;
use serde_json::Value;
use structable_derive::StructTable;

/// Command without description in OpenAPI
///
#[derive(Args)]
pub struct PropertyCommand {
    /// Request Query parameters
    #[command(flatten)]
    query: QueryParameters,

    /// Path parameters
    #[command(flatten)]
    path: PathParameters,
}

/// Query parameters
#[derive(Args)]
struct QueryParameters {}

/// Path parameters
#[derive(Args)]
struct PathParameters {
    /// namespace_name parameter for
    /// /v2/metadefs/namespaces/{namespace_name}/properties/{property_name} API
    ///
    #[arg(
        help_heading = "Path parameters",
        id = "path_param_namespace_name",
        value_name = "NAMESPACE_NAME"
    )]
    namespace_name: String,

    /// property_name parameter for
    /// /v2/metadefs/namespaces/{namespace_name}/properties/{property_name} API
    ///
    #[arg(
        help_heading = "Path parameters",
        id = "path_param_property_name",
        value_name = "PROPERTY_NAME"
    )]
    property_name: String,
}
/// Property response representation
#[derive(Deserialize, Serialize, Clone, StructTable)]
struct ResponseData {
    #[serde(rename = "additionalItems")]
    #[structable(optional, title = "additionalItems")]
    additional_items: Option<bool>,

    #[serde(rename = "default")]
    #[structable(optional, pretty, title = "default")]
    _default: Option<Value>,

    #[serde()]
    #[structable(optional)]
    description: Option<String>,

    #[serde(rename = "enum")]
    #[structable(optional, pretty, title = "enum")]
    _enum: Option<Value>,

    #[serde()]
    #[structable(optional, pretty)]
    items: Option<Value>,

    #[serde()]
    #[structable(optional)]
    maximum: Option<f32>,

    #[serde(rename = "maxItems")]
    #[structable(optional, title = "maxItems")]
    max_items: Option<i32>,

    #[serde(rename = "maxLength")]
    #[structable(optional, title = "maxLength")]
    max_length: Option<i32>,

    #[serde()]
    #[structable(optional)]
    minimum: Option<f32>,

    #[serde(rename = "minItems")]
    #[structable(optional, title = "minItems")]
    min_items: Option<i32>,

    #[serde(rename = "minLength")]
    #[structable(optional, title = "minLength")]
    min_length: Option<i32>,

    #[serde()]
    #[structable()]
    name: String,

    #[serde()]
    #[structable(optional, pretty)]
    operators: Option<Value>,

    #[serde()]
    #[structable(optional)]
    pattern: Option<String>,

    #[serde()]
    #[structable(optional)]
    readonly: Option<bool>,

    #[serde()]
    #[structable(optional, pretty)]
    required: Option<Value>,

    #[serde()]
    #[structable()]
    title: String,

    #[serde(rename = "type")]
    #[structable(title = "type")]
    _type: String,

    #[serde(rename = "uniqueItems")]
    #[structable(optional, title = "uniqueItems")]
    unique_items: Option<bool>,
}

impl PropertyCommand {
    /// Perform command action
    pub async fn take_action(
        &self,
        parsed_args: &Cli,
        client: &mut AsyncOpenStack,
    ) -> Result<(), OpenStackCliError> {
        info!("Show Property");

        let op = OutputProcessor::from_args(parsed_args);
        op.validate_args(parsed_args)?;

        let mut ep_builder = get::Request::builder();

        // Set path parameters
        ep_builder.namespace_name(&self.path.namespace_name);
        ep_builder.property_name(&self.path.property_name);
        // Set query parameters
        // Set body parameters

        let ep = ep_builder
            .build()
            .map_err(|x| OpenStackCliError::EndpointBuild(x.to_string()))?;

        let data = ep.query_async(client).await?;
        op.output_single::<ResponseData>(data)?;
        Ok(())
    }
}
