Output doc/source/images/tui/ostui.gif

Set FontSize 12
Set Width 1400
Set Height 1000
Set TypingSpeed 0.1
Set Padding 0
Set WindowBar Colorful

Type "ostui --os-cloud dev-admin"
Sleep 1s
Enter
Sleep 3s
# switch to images
Type ":"
Sleep 1
Type "ima"
Sleep 2
Enter
Sleep 3
Down 2
Sleep 2
# describe
Type "y"
Sleep 2
Escape
Sleep 2
# switch to security groups
Type ":"
Sleep 500ms
Type "sg"
Sleep 500ms
Sleep 1s
Enter
Sleep 2
Down 2
Sleep 2
# list sg rules
Type "l"
Sleep 2
