# Partial file included by cargo-dist into the generated workflow
#
- name: Harden Runner
  uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
  with:
    egress-policy: audit
