# Partial file included by cargo-dist into the generated workflow
#
- name: Harden Runner
  uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
  with:
    egress-policy: audit
